### ISSUE TITLE
Error on Executing

### ISSUE THREAD

**Issue by h2o-commits** [derhuerst/eco-counter-client#16] opened 2022-07-15 13:27 UTC
After nodejs test.js get an Error:

not ok 1 Error: Not Found
  ---
    operator: error
    stack: |-
      Error: Not Found
          at /home/pi/Nextcloud/Raspberry-Sync/progs/fahrrad-counter/eco-counter-client/lib/request.js:39:16
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ...

ideas? thx

**Comment by derhuerst** [comment] 2022-07-15 13:45
This is because the Eco Counter API has changed, and nobody has adapted it so far. See #15 for details.

At https://github.com/derhuerst/eco-counter-client/issues/15#issuecomment-924041358, I have posted more up-to-date API requests.

**Comment by derhuerst** [comment] 2022-07-15 13:46
I'm going to close this as a duplicate of #15, feel free to follow it for updates or contribute a new implementation!

**Closed as completed by derhuerst** 2022-07-15 13:46 UTC
Labels: duplicate
